version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - ecoride-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8090"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - ecoride-net

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ecoride}
      MYSQL_USER: ${MYSQL_USER:-ecorider}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-securepass}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ecoride-net

  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-ecoride_nosql}
    volumes:
      - mongo_data:/data/db
    networks:
      - ecoride-net
    ports:
      - "27017:27017"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - frontend
      - backend
    networks:
      - ecoride-net

  # Service de tests unitaires indépendant
  tests:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.tests
    volumes:
      - ./backend:/var/www/html
      - composer_cache:/root/.composer/cache
    depends_on:
      - mysql
    networks:
      - ecoride-net
    environment:
      APP_ENV: "testing"
      DB_CONNECTION: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "${MYSQL_DATABASE_TEST:-ecoride_test}"
      DB_USERNAME: "${MYSQL_USER:-ecorider}"
      DB_PASSWORD: "${MYSQL_PASSWORD:-securepass}"
    # Ce service ne démarre pas automatiquement, il faut l'exécuter manuellement avec:
    # docker-compose run tests
    profiles:
      - tests
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-ecorider}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-securepass}
    depends_on:
      - mysql
    networks:
      - ecoride-net

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-mongo}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-changeme}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:-mongo}:${MONGO_PASSWORD:-changeme}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-pass}
    depends_on:
      - mongodb
    networks:
      - ecoride-net

volumes:
  db_data:
  mongo_data:
<<<<<<< HEAD
=======
  composer_cache:
>>>>>>> develop

networks:
  ecoride-net:
    driver: bridge
