services:
  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - ecoride-net
    environment:
      - VITE_API_URL=http://localhost:8080/api
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - ecoride-net

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ecoride}
      MYSQL_USER: ${MYSQL_USER:-ecorider}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-securepass}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ecoride-net

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - ecoride-net

  # Service de tests unitaires indépendant
  tests:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.tests
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    networks:
      - ecoride-net
    environment:
      APP_ENV: "testing"
      DB_CONNECTION: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "${MYSQL_DATABASE_TEST:-ecoride_test}"
      DB_USERNAME: "${MYSQL_USER:-ecorider}"
      DB_PASSWORD: "${MYSQL_PASSWORD:-securepass}"
    # Ce service ne démarre pas automatiquement, il faut l'exécuter manuellement avec:
    # docker-compose run tests
    profiles:
      - tests
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-ecorider}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-securepass}
    depends_on:
      - mysql
    networks:
      - ecoride-net

volumes:
  db_data:

networks:
  ecoride-net:
    driver: bridge 