#!/bin/sh
if command -v pwsh >/dev/null 2>&1; then
  pwsh -NoProfile -ExecutionPolicy Bypass -File "$0.ps1" "$@"
else
  . "$(dirname "$0")/_/husky.sh"
  # Exécuter le build avant de pousser les modifications
  npm run build
fi 
