#!/bin/sh
# Utiliser uniquement PowerShell sur Windows
pwsh -NoProfile -ExecutionPolicy Bypass -File "$0.ps1" "$@"

# Exécuter les outils de la racine du projet
npm run lint
npm run format

# Exécuter les outils spécifiques à frontend/  
cd frontend
npm run lint
npm run format
cd ..

# Exécution de lint-staged pour les fichiers modifiés uniquement
npm run lint-staged
