# CI/CD pipeline EcoRide – optimisation & écoconception
name: CI/CD EcoRide

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: eco-ride-${{ github.ref }}
  cancel-in-progress: false

env:
  NODE_VERSION: '18'
  PHP_VERSION: '8.1'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache front dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
      - name: Install front dependencies
        run: cd frontend && npm ci
      - name: Lint front
        run: cd frontend && npm run lint
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Cache back dependencies
        uses: actions/cache@v3
        with:
          path: backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
      - name: Install back dependencies
        run: cd backend && composer install --no-progress --no-suggest --prefer-dist
      - name: Lint back
        run: cd backend && vendor/bin/phpcs 